config/routes.rb
Rails.application.routes.draw do
  post 'like/:micropost_id' => 'likes#like', as: 'like'
  delete 'unlike/:micropost_id' => 'likes#unlike', as: 'unlike'
  
  
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get "/tweet" => "tweet#timeline"
  get "/signout_twitter" => "sessions#destroy"
  
  get "/auth/:provider/callback" => "sessions#create" 

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy, :show]
  resources :relationships, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  end

app/views/shared/_comment_form.html.erb
<%= form_for(@comment, html: { multipart: true }) do |f| %>
<%= render 'shared/error_messages', object: f.object%>

<div class="field">
  <span class="count">

  </span>
  <%= f.text_area :content, placeholder: "Compose new comment..."%>
</div>
<%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_detail.html.erb
<div class="comment form">
<%= render 'shared/comment_form'%>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
  <div class="alert alert_danger">
    The form contains <%= pluralize(object.errors.count, "error") %>.
  </div>
  <ul>
    <% object.errors.full_messages.each do |msg|%>
    <li>
      <%= msg %>
    </li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost, html: { multipart: true }) do |f| %>
<%= render 'shared/error_messages', object: f.object%>

<div class="field">
  <span class="count">
<script type="text/javascript" src="maxlength.js">
</script>
  </span>
  <%= f.text_area :content, placeholder: "Compose new micropost..."%>
</div>
<%= f.submit "Post", class: "btn btn-primary" %>
<span class="picture">
  <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
</span>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= users_path(@user) %>" >
    <strong id="microposts" class="stat">
      <%= @user.microposts.count %>
      </strong>
      <% if @user.microposts.count > 1 then %>
      microposts
      <% else  %>
      micropost
      <% end %>
      </a>
  <a href="<% following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<% followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
  
  
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>