config/routes.rb
Rails.application.routes.draw do
  post 'like/:micropost_id' => 'likes#like', as: 'like'
  delete 'unlike/:micropost_id' => 'likes#unlike', as: 'unlike'
  
  
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get "/tweet" => "tweet#timeline"
  get "/signout_twitter" => "sessions#destroy"
  
  get "/auth/:provider/callback" => "sessions#create" 

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy, :show]
  resources :relationships, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments
  has_many :taggings
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true, length: {maximum: 140}
  validate :picture_size
  
  def like_user(user_id)
   likes.find_by(user_id: user_id)
  end
  
  private
  
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end
  
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
    before_action :logged_in_user, only: [:create, :destroy]
    before_action :correct_user, only: :destroy
  
  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end
  
  def destroy
    @micropost.destroy
    flash[:success] = "Micropost deleted!"
    redirect_to request.referrer || root_url
  end
  
  def show
    # params id からmicropostの情報を検索
    @micropost = Micropost.find(params[:id])
    @comments = @micropost.comments
    @comment = Comment.new
  end

  
  private

    def micropost_params
      params.require(:micropost).permit(:content, :picture)
    end
    
    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content">
    <%= micropost.content %>
    <%= image_tag micropost.picture.url if micropost.picture? %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    
    <% if current_user?(micropost.user) %>
    <%= link_to "delete", micropost, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
    <% if micropost.like_user(current_user.id)%>
      <%= link_to 'unlike', unlike_path(micropost.id), method: :delete %>
    <% else %>
      <%= link_to 'like', like_path(micropost.id), method: :post %>
    <% end %>
      <%= link_to 'comment', micropost_path(micropost.id) %>
  </span>
</li>

app/views/microposts/show.html.erb
<div class="col-md-4">
  <%= form_for(@comment, html: { multipart: true }) do |f| %>
    <%= render 'shared/error_messages', object: f.object%>
    <div class="field">
      <%= hidden_field_tag 'id', @micropost.id %>
      <%= f.text_area :comment, placeholder: "Compose new comment..."%>
    </div>
  <%= f.submit "Comment", class: "btn btn-primary" %>
<% end %>
</div>

<div class="col-md-8">
  <ol class="microposts" >
    <% @comments.each do |c| %>
      <% user = User.find(c.user_id)  %>
      <li>
        <%= link_to gravatar_for(user, size: 50), user %>
        <span class="user"><%= link_to user.name, user %></span>
        <span class="content"><%= c.comment %></span>
        <span class="timestamp">Commented <%= time_ago_in_words(c.created_at) %> ago.</span>
      </li>
    <% end %>
  </ol>
</div>